name: test-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pandas>=1.0
  - numpy>=1.16
  - scipy>=1.1
  - scikit-learn>=0.23
  - seaborn>=0.11
  - plotly>=4.0
  # Test
  - pytest>=6.0.0
  - pytest-cov>=2.6.0
  - nbconvert<6.0.0 # For pytest-notebook https://github.com/chrisjsewell/pytest-notebook/issues/10
  - mock>=4.0
  # Optional
  - gensim>=3.4.0
  - pyldavis>=2.1.2
  - nltk>=3.4
  - gcsfs>=0.2.1
  - hdbscan>=0.8.20
  - ipython>=7.5.0
  - xlrd>=1.2.0
  - paramiko>=2.4.2
  - papermill>=2.1.2
  - statsmodels>=0.11.1
  - modin>=0.8.2
  - pip>=20.0.0
  - tqdm>=4.49.0
  - pip:
      - google-cloud-storage>=1.18.0
      - presidio-analyzer==0.3.8917rc0
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.2.0/en_core_web_lg-2.2.0.tar.gz # For presidio
      - pyscagnostics>=0.1.0a4
      - pytest-notebook>=0.6.1
